apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: promotions-ingress
  labels:
    app: promotions
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: promotions-service
                port:
                  number: 80
